<?php

$form = $this->form;
$form->setAttribute('action', 'login');
$form->prepare();


    if (isset($loginMsg[0])){ 
        unset($loginMsg[0]); 
?>
        <div class="alert alert-danger col-md-4 col-md-offset-4 alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <span class="glyphicon glyphicon-exclamation-sign"></span> Mauvais mot de passe ou identifiant!
        </div>
<?php }else if (isset($formenonvalide)){ 
            unset($formenonvalide); ?>
            <div class="alert alert-danger col-md-4 col-md-offset-4 alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <span class="glyphicon glyphicon-exclamation-sign"></span> Les informations doivent faire 3 caractères minimum!
            </div>
<?php
}else if (isset($aurevoir)){ 
            unset($aurevoir); ?>
            <div class="alert alert-success col-md-4 col-md-offset-4 alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <span class="glyphicon glyphicon-exclamation-sign"></span> Vous avez été déconnecté avec succès!
            </div> 
<?php } ?>

<?php echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title text-center">Veuillez vous connecter <i class="fa fa-key"></i></h3>
            </div>
            <div class="panel-body">
                <form role="form">
                    <fieldset>
                        <div class="form-group">
                            <?php echo $this->formEmail($form->get('mail')); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formPassword($form->get('password')); ?>
                        </div>
                        <?php echo $this->formElement($form->get('csrf')); ?>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
    

