<?php
$form = $this->form;
$form->prepare();


if(count($flashMessages)) : ?>

    <?php foreach ($flashMessages as $msg) : ?>
    <div class="alert alert-danger col-md-6 col-md-offset-3 alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <span class="glyphicon glyphicon-exclamation-sign"></span> <?php echo $msg; ?>
    </div>
    <?php endforeach;  ?>

<?php endif;


echo $this->form()->openTag($form); 
?>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title text-center"> Rejoignez nous <i class="fa fa-smile-o"></i></h3>
            </div>
            <div class="panel-body">
                    <fieldset>
                        <div class="form-group">
                            <?php
                            echo $this->formText($form->get('prenom'));
                            ?>
                        </div>
                        <div class="form-group">
                            <?php
                            echo $this->formText($form->get('nom'));
                            ?>
                        </div>
                        <div class="form-group">
                            <?php
                            echo $this->formEmail($form->get('mail'));
                            ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formPassword($form->get('password')); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formPassword($form->get('password2')); ?>
                        </div>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </fieldset>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>





